### ISSUE TITLE
Default Selected Value

### ISSUE THREAD

**Issue by amrrs** [balexbyrd/sense-FieldUI#14]
Hi, Wonderful job with the Extension. But I'm struggling in setting a 'Default Selected Value' Not sure if it should be an expression or it would be a constant value?

Could you please help?

**Comment by geck123** [comment]
Another issue with 'Default Selected Value':

I entered a value for 'Default Selected Value'.  However, the drop-down list does not select the 'Default Selected Value' as default, as soon as I press "Done" with the Edit.  Instead, I need to refresh the page in order to show the 'Default Selected Value'.

Could you please fix this?  Thanks.

**Comment by balexbyrd** [comment]
Closing as it's a duplicate of #8
