### ISSUE TITLE
The dropdown border is chopping off while rendering as dropdown

### ISSUE THREAD

**Issue by Innocent84** [balexbyrd/sense-FieldUI#9]
Hi Team,

The dropdown border is chopping off while rendering as dropdown, and the dropdown is aligned at bottom instead of center alignemnt
![alignment issue](https://user-images.githubusercontent.com/29543939/27286101-fa7caba0-54cc-11e7-96de-0ff8147e42aa.PNG)
. This has happened after upgrading to V3.2.4. Even while rendering as button the buttons are aligned on bottom instead of center of the component.

**Comment by balexbyrd** [comment]
I can replicate this issue on my end as well. The problem is with the way Qlik leaves padding / space for the titles using a <header> tag. 

As you probably know, a workaround is to just increase the height of the box, but then there's generally too much whitespace and screen space is valuable.

It looks like you're choosing dates, maybe this extension is a better option? http://branch.qlik.com/#!/project/5697a878dcc497f80ed514bf

When I have some time I'll work on this one and add it to a new release.
